"""
reports/generator.py — PDF quality report generator.

Produces professional single-page quality reports using ReportLab.
Falls back gracefully if ReportLab is not installed (outputs JSON instead).
"""

from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path
from typing import Optional

from core.logging import get_logger

log = get_logger(__name__)

_OUTPUT_DIR = Path("reports/output")
_OUTPUT_DIR.mkdir(parents=True, exist_ok=True)


class ReportGenerator:
    """
    Generates a PDF quality inspection report.

    If ReportLab (reportlab) is available the output is a proper PDF.
    If not, a JSON fallback is written with a .json extension so the
    system degrades gracefully during development.
    """

    def generate(
        self,
        report_id: int,
        title: str,
        from_dt: datetime,
        to_dt: datetime,
        summary: dict,
        pareto: list[dict],
        severity_dist: list[dict],
        generated_by: str = "system",
    ) -> Path:
        """
        Generate the report and write it to `reports/output/`.

        Returns the Path to the written file.
        """
        try:
            from reportlab.lib import colors
            from reportlab.lib.pagesizes import A4
            from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
            from reportlab.lib.units import cm
            from reportlab.platypus import (
                SimpleDocTemplate,
                Paragraph,
                Spacer,
                Table,
                TableStyle,
            )

            return self._generate_pdf(
                report_id=report_id,
                title=title,
                from_dt=from_dt,
                to_dt=to_dt,
                summary=summary,
                pareto=pareto,
                severity_dist=severity_dist,
                generated_by=generated_by,
                reportlab_modules={
                    "colors": colors,
                    "A4": A4,
                    "getSampleStyleSheet": getSampleStyleSheet,
                    "ParagraphStyle": ParagraphStyle,
                    "cm": cm,
                    "SimpleDocTemplate": SimpleDocTemplate,
                    "Paragraph": Paragraph,
                    "Spacer": Spacer,
                    "Table": Table,
                    "TableStyle": TableStyle,
                },
            )

        except ImportError:
            log.warning("reportlab_not_installed_falling_back_to_json")
            return self._generate_json_fallback(
                report_id=report_id,
                title=title,
                from_dt=from_dt,
                to_dt=to_dt,
                summary=summary,
                pareto=pareto,
                severity_dist=severity_dist,
                generated_by=generated_by,
            )

    # ------------------------------------------------------------------ #
    # PDF generation (requires reportlab)
    # ------------------------------------------------------------------ #

    def _generate_pdf(self, report_id, title, from_dt, to_dt, summary,
                      pareto, severity_dist, generated_by, reportlab_modules) -> Path:
        rl = reportlab_modules
        output_path = _OUTPUT_DIR / f"report_{report_id}.pdf"

        doc = rl["SimpleDocTemplate"](
            str(output_path),
            pagesize=rl["A4"],
            rightMargin=2 * rl["cm"],
            leftMargin=2 * rl["cm"],
            topMargin=2 * rl["cm"],
            bottomMargin=2 * rl["cm"],
        )

        styles = rl["getSampleStyleSheet"]()
        story = []

        # Title
        story.append(rl["Paragraph"](title, styles["Title"]))
        story.append(rl["Spacer"](1, 0.3 * rl["cm"]))

        # Header info
        story.append(rl["Paragraph"](
            f"Period: {from_dt.strftime('%Y-%m-%d %H:%M')} – {to_dt.strftime('%Y-%m-%d %H:%M')} UTC",
            styles["Normal"],
        ))
        story.append(rl["Paragraph"](
            f"Generated by: {generated_by} | Generated at: {datetime.utcnow().strftime('%Y-%m-%d %H:%M')} UTC",
            styles["Normal"],
        ))
        story.append(rl["Spacer"](1, 0.5 * rl["cm"]))

        # Summary table
        story.append(rl["Paragraph"]("Summary", styles["Heading2"]))
        summary_data = [
            ["Metric", "Value"],
            ["Total Inspections", str(summary.get("total_inspections", 0))],
            ["Defect Rate", f"{summary.get('defect_rate', 0) * 100:.1f}%"],
            ["Avg Latency", f"{summary.get('avg_latency_ms', 0):.1f} ms"],
        ]
        for verdict, count in summary.get("by_verdict", {}).items():
            summary_data.append([f"  {verdict}", str(count)])

        summary_table = rl["Table"](summary_data, colWidths=[10 * rl["cm"], 6 * rl["cm"]])
        summary_table.setStyle(rl["TableStyle"]([
            ("BACKGROUND", (0, 0), (-1, 0), rl["colors"].HexColor("#2E86AB")),
            ("TEXTCOLOR", (0, 0), (-1, 0), rl["colors"].whitesmoke),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [rl["colors"].white, rl["colors"].HexColor("#F5F5F5")]),
            ("GRID", (0, 0), (-1, -1), 0.5, rl["colors"].grey),
            ("PADDING", (0, 0), (-1, -1), 6),
        ]))
        story.append(summary_table)
        story.append(rl["Spacer"](1, 0.5 * rl["cm"]))

        # Defect Pareto
        if pareto:
            story.append(rl["Paragraph"]("Defect Distribution (Pareto)", styles["Heading2"]))
            pareto_data = [["Defect Class", "Count"]] + [
                [p["class_name"].replace("_", " ").title(), str(p["count"])]
                for p in pareto
            ]
            pareto_table = rl["Table"](pareto_data, colWidths=[10 * rl["cm"], 6 * rl["cm"]])
            pareto_table.setStyle(rl["TableStyle"]([
                ("BACKGROUND", (0, 0), (-1, 0), rl["colors"].HexColor("#E84855")),
                ("TEXTCOLOR", (0, 0), (-1, 0), rl["colors"].whitesmoke),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [rl["colors"].white, rl["colors"].HexColor("#FFF0F0")]),
                ("GRID", (0, 0), (-1, -1), 0.5, rl["colors"].grey),
                ("PADDING", (0, 0), (-1, -1), 6),
            ]))
            story.append(pareto_table)
            story.append(rl["Spacer"](1, 0.5 * rl["cm"]))

        # Severity Distribution
        if severity_dist:
            story.append(rl["Paragraph"]("Severity Distribution", styles["Heading2"]))
            sev_data = [["Grade", "Count"]] + [
                [s["grade"], str(s["count"])] for s in severity_dist
            ]
            sev_table = rl["Table"](sev_data, colWidths=[10 * rl["cm"], 6 * rl["cm"]])
            sev_table.setStyle(rl["TableStyle"]([
                ("BACKGROUND", (0, 0), (-1, 0), rl["colors"].HexColor("#3D405B")),
                ("TEXTCOLOR", (0, 0), (-1, 0), rl["colors"].whitesmoke),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [rl["colors"].white, rl["colors"].HexColor("#F0F0FF")]),
                ("GRID", (0, 0), (-1, -1), 0.5, rl["colors"].grey),
                ("PADDING", (0, 0), (-1, -1), 6),
            ]))
            story.append(sev_table)

        doc.build(story)
        log.info("pdf_generated", path=str(output_path))
        return output_path

    # ------------------------------------------------------------------ #
    # JSON fallback (no reportlab)
    # ------------------------------------------------------------------ #

    def _generate_json_fallback(self, report_id, title, from_dt, to_dt,
                                summary, pareto, severity_dist,
                                generated_by) -> Path:
        output_path = _OUTPUT_DIR / f"report_{report_id}.json"
        data = {
            "report_id": report_id,
            "title": title,
            "generated_by": generated_by,
            "generated_at": datetime.utcnow().isoformat(),
            "period": {"from": from_dt.isoformat(), "to": to_dt.isoformat()},
            "summary": summary,
            "pareto": pareto,
            "severity_distribution": severity_dist,
            "_note": "ReportLab not installed — install 'reportlab' for PDF output.",
        }
        with output_path.open("w", encoding="utf-8") as fh:
            json.dump(data, fh, indent=2)
        log.info("json_report_generated", path=str(output_path))
        return output_path
