"""initial_schema

Revision ID: 48c67d12ffca
Revises: 
Create Date: 2026-03-21 22:45:33.330533

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48c67d12ffca'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inspections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=64), nullable=True),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('verdict', sa.String(length=16), nullable=False),
    sa.Column('escalated', sa.Boolean(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspections_product_id'), 'inspections', ['product_id'], unique=False)
    op.create_index(op.f('ix_inspections_timestamp'), 'inspections', ['timestamp'], unique=False)
    op.create_index(op.f('ix_inspections_verdict'), 'inspections', ['verdict'], unique=False)
    op.create_table('model_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('version_tag', sa.String(length=32), nullable=False),
    sa.Column('detector_path', sa.String(length=256), nullable=False),
    sa.Column('classifier_path', sa.String(length=256), nullable=False),
    sa.Column('map50', sa.Float(), nullable=True),
    sa.Column('top1_accuracy', sa.Float(), nullable=True),
    sa.Column('trained_at', sa.DateTime(), nullable=True),
    sa.Column('deployed_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('rollback_to', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_tag')
    )
    op.create_index(op.f('ix_model_versions_is_active'), 'model_versions', ['is_active'], unique=False)
    op.create_table('quality_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('report_type', sa.String(length=16), nullable=True),
    sa.Column('from_dt', sa.DateTime(), nullable=False),
    sa.Column('to_dt', sa.DateTime(), nullable=False),
    sa.Column('total_inspections', sa.Integer(), nullable=True),
    sa.Column('pass_count', sa.Integer(), nullable=True),
    sa.Column('fail_count', sa.Integer(), nullable=True),
    sa.Column('defect_rate', sa.Float(), nullable=True),
    sa.Column('remedy_save_rate_pct', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('pdf_path', sa.String(length=256), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('generated_by', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('defects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('inspection_id', sa.String(length=36), nullable=False),
    sa.Column('class_name', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('bbox_x1', sa.Float(), nullable=False),
    sa.Column('bbox_y1', sa.Float(), nullable=False),
    sa.Column('bbox_x2', sa.Float(), nullable=False),
    sa.Column('bbox_y2', sa.Float(), nullable=False),
    sa.Column('bbox_area_ratio', sa.Float(), nullable=True),
    sa.Column('severity_grade', sa.String(length=4), nullable=True),
    sa.Column('severity_score', sa.Float(), nullable=True),
    sa.Column('uq_mean', sa.Float(), nullable=True),
    sa.Column('uq_std', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_defects_class_name'), 'defects', ['class_name'], unique=False)
    op.create_index(op.f('ix_defects_inspection_id'), 'defects', ['inspection_id'], unique=False)
    op.create_table('remediation_actions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('inspection_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('station', sa.String(length=4), nullable=True),
    sa.Column('is_remediable', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inspection_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('remediation_actions')
    op.drop_index(op.f('ix_defects_inspection_id'), table_name='defects')
    op.drop_index(op.f('ix_defects_class_name'), table_name='defects')
    op.drop_table('defects')
    op.drop_table('quality_reports')
    op.drop_index(op.f('ix_model_versions_is_active'), table_name='model_versions')
    op.drop_table('model_versions')
    op.drop_index(op.f('ix_inspections_verdict'), table_name='inspections')
    op.drop_index(op.f('ix_inspections_timestamp'), table_name='inspections')
    op.drop_index(op.f('ix_inspections_product_id'), table_name='inspections')
    op.drop_table('inspections')
    # ### end Alembic commands ###
