backbone: wide_resnet50_2
feature_layers:
- layer2
- layer3
feature_dim: 8
image_size: 384
coreset_ratio: 0.01
k_nearest: 9
n_train_patches: 1512
n_train_features: 96768
threshold: 2.792120933532715
auroc: 0.6422764227642277
